description: |
  Alpine-based Docker image containing the `shellcheck` binary:
  https://hub.docker.com/r/koalaman/shellcheck

parameters:
  tag:
    type: string
    default: v0.7.1
    description: >
      Tag of the koalaman/shellcheck image to use:
      https://hub.docker.com/r/koalaman/shellcheck/tags

docker:
  - image: koalaman/shellcheck:<<parameters.tag>>
