description: |
  Alpine-based Docker image containing the `shellcheck` binary:
  https://hub.docker.com/r/koalaman/shellcheck-alpine

parameters:
  tag:
    type: string
    default: v0.7.1
    description: >
      Tag of the koalaman/shellcheck-alpine image to use:
      https://hub.docker.com/r/koalaman/shellcheck-alpine/tags

docker:
  - image: koalaman/shellcheck-alpine:<<parameters.tag>>
