description: |
    Select the version of the CircleCI Base Image to use, along with resource class

parameters:
    image-tag:
        type: string
        default: "current"
        description: |
            Shellcheck is included in the CircleCI authored `cimg/base` docker image (Feb 2022 onward), installed via the official Ubuntu packages.
            By default the most current stable release of this image will be used, but you may statically set the image tag with this parameter.
            https://circleci.com/developer/images/image/cimg/base
    resource_class:
        type: enum
        default: large
        description: Configure the executor resource class
        enum: ["small", "medium", "medium+", "large", "xlarge", "2xlarge", "2xlarge+"]
docker:
    - image: cimg/base:<<parameters.image-tag>>
resource_class: << parameters.resource_class >>
